# Remote state backend (generated by scripts/create-env.sh or manually after bootstrap).
# Uses DigitalOcean Spaces (S3-compatible).
#
# Required env vars for init:
#   AWS_ACCESS_KEY_ID     = Spaces access key
#   AWS_SECRET_ACCESS_KEY = Spaces secret key
#
terraform {
  backend "s3" {
    endpoints = {
      s3 = "https://{{SPACES_REGION}}.digitaloceanspaces.com"
    }
    bucket                      = "{{STATE_BUCKET}}"
    key                         = "{{ENV}}/terraform.tfstate"
    region                      = "us-east-1"
    skip_credentials_validation = true
    skip_requesting_account_id  = true
    skip_metadata_api_check     = true
    skip_region_validation      = true
    skip_s3_checksum            = true
  }
}
